Repository DeepLink-org/dlinfer, pull requests merged in 2025-02, with the labels that each got.

#168 fix: upspeed graph mode compilation
  dlinfer/graph/dicp/dynamo_bridge/compile_fx.py
  dlinfer/graph/dicp/dynamo_bridge/operator.py
Labels: enhancement

#170 [ascend]optimize internal tensor lifetime management in AtbGraph
  dlinfer/graph/dicp/vendor/AtbGraph/codegen/runtime/model.cpp
  dlinfer/graph/dicp/vendor/AtbGraph/codegen/runtime/model.h
Labels: ascend

#143 [ascend] optimize tp > 1 latency in graph mode
  dlinfer/graph/dicp/vendor/AtbGraph/codegen/atb_graph.py
  dlinfer/graph/dicp/vendor/AtbGraph/codegen/runtime/model.cpp
  dlinfer/graph/dicp/vendor/AtbGraph/codegen/runtime/model.h
  dlinfer/graph/dicp/vendor/AtbGraph/compile_job.py
  dlinfer/graph/dicp/vendor/AtbGraph/conversion.py
Labels: ascend

#171 [ascend] feat: use swiglu in atb graph
  dlinfer/graph/dicp/vendor/AtbGraph/atb_op.py
  dlinfer/graph/dicp/vendor/AtbGraph/codegen/atb_infer_param.py
  dlinfer/graph/dicp/vendor/AtbGraph/codegen/atb_op.py
  dlinfer/graph/dicp/vendor/AtbGraph/codegen/runtime/ops/atb_ops/rms_norm.cpp
  dlinfer/graph/dicp/vendor/AtbGraph/conversion.py
Labels: ascend

#151 [feature] add dlinfer w8a8 support.
  dlinfer/ops/llm.py
  dlinfer/vendor/maca/maca_ops.py
Labels: enhancement

#172 [ascend] refactor parse atb graph
  dlinfer/graph/dicp/vendor/AtbGraph/codegen/atb.py
  dlinfer/graph/dicp/vendor/AtbGraph/codegen/atb_graph.py
  dlinfer/graph/dicp/vendor/AtbGraph/codegen/atb_op.py
  dlinfer/graph/dicp/vendor/AtbGraph/codegen/runtime/model.cpp
  dlinfer/graph/dicp/vendor/AtbGraph/codegen/runtime/utils/global_dict.cpp
  dlinfer/graph/dicp/vendor/AtbGraph/codegen/runtime/utils/global_dict.h
  dlinfer/graph/dicp/vendor/AtbGraph/ext_ops.py
Labels: ascend

#133 [maca] support deepseekv2 for maca backend.
  dlinfer/vendor/maca/context_flashattention.py
  dlinfer/vendor/maca/csrc/CMakeLists.txt
  dlinfer/vendor/maca/csrc/attention/attention_kernels.cu
  dlinfer/vendor/maca/csrc/cache_kernels.cu
  dlinfer/vendor/maca/csrc/pybind.cpp
  dlinfer/vendor/maca/maca_ops.py
Labels: maca

#173 [camb]fix fused_moe param order
  dlinfer/vendor/camb/camb_ops.py
Labels: bug, camb
