Repository DeepLink-org/dlinfer, pull requests merged in 2025-01, with the labels that each got.

#148 [maca] add lmdeploy cudagraph patch for maca.
  dlinfer/framework/lmdeploy_ext/__init__.py
  dlinfer/framework/lmdeploy_ext/cudagraph/__init__.py
  dlinfer/framework/lmdeploy_ext/cudagraph/maca_cudagraph.py
Labels: maca

#146 modify interface of paged_prefiil_attention
  dlinfer/graph/dicp/vendor/AtbGraph/conversion.py
  dlinfer/ops/llm.py
  dlinfer/vendor/ascend/torch_npu_ops.py
  dlinfer/vendor/maca/maca_ops.py
Labels: enhancement

#163 [ascend] fix qwen2_vl graph_mode
  dlinfer/framework/lmdeploy_ext/dynamo/graph_mode_patch.py
  dlinfer/graph/dicp/vendor/AtbGraph/__init__.py
  dlinfer/graph/dicp/vendor/AtbGraph/atb_op.py
  dlinfer/graph/dicp/vendor/AtbGraph/codegen/atb_graph.py
  dlinfer/graph/dicp/vendor/AtbGraph/codegen/atb_infer_param.py
  dlinfer/graph/dicp/vendor/AtbGraph/codegen/atb_op.py
  dlinfer/graph/dicp/vendor/AtbGraph/codegen/runtime/ops/custom_ops/zeros_like_operation.cpp
  dlinfer/graph/dicp/vendor/AtbGraph/codegen/runtime/ops/custom_ops/zeros_like_operation.h
  dlinfer/graph/dicp/vendor/AtbGraph/codegen/runtime/ops/custom_ops/zeros_operation.cpp
  dlinfer/graph/dicp/vendor/AtbGraph/codegen/runtime/ops/custom_ops/zeros_operation.h
  dlinfer/graph/dicp/vendor/AtbGraph/conversion.py
  tests/test_lmdeploy/e2e/config.yaml
  tests/test_lmdeploy/e2e/test_model_tp1.py
  tests/test_lmdeploy/utils/pipeline_chat.py
Labels: ascend
